### ISSUE TITLE
Split icons into its own module/repository

### ISSUE THREAD

**Issue by mariuslundgard** [popeindustries/buddy#84]
Split icons to a `@nrk/icons` module for easier maintenance and consumption.

Then `@nrk/bjartmar` would no longer need to manage SVG compression (which is typically not handled by build tools such as buddy, webpack, etc.).

This will make `@nrk/bjartmar` a pure CSS framework.

**Comment by mariuslundgard** [comment]
OMG, this was the wrong repository. Sorry about that!

**Comment by popeindustries** [comment]
Ha! For what its worth, I agree with you!
